import express from 'express'
import { get, all, run, uid, now } from './db.js'
import { register, login, sign, verify, authMiddleware, publicUser, httpError, COOKIE, restrictionOf } from './auth.js'
import { sendToUsers } from './hub.js'
import { presence, getStatus, voiceSnapshot, userVoiceChannel } from './state.js'
import { BADGES, BADGE_IDS, permsOf } from '../shared/badges.js'

export const router = express.Router()
const wrap = fn => (req,res,next) => { try { fn(req,res,next) } catch(e) { next(e) } }
function requireAdmin(req,res,next){if(!req.user.admin)return res.status(403).json({error:'Только для администраторов платформы'});next()}
export function userPerms(u){if(!u)return new Set();if(u.admin)return new Set(['suspend','ban','delete_any_message','grant_badges']);let ids=[];try{ids=u.badges?JSON.parse(u.badges):[]}catch{}return new Set(permsOf(Array.isArray(ids)?ids:[]))}
function requirePerm(perm){return(req,res,next)=>{if(!userPerms(req.user).has(perm))return res.status(403).json({error:'Недостаточно прав модерации'});next()}}
function guardTarget(req){const t=get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!t)throw httpError(404,'Пользователь не найден');if(t.id===req.user.id)throw httpError(400,'Нельзя применить ограничение к себе');if(t.admin&&!req.user.admin)throw httpError(403,'Нельзя модерировать администратора платформы');return t}
function pushRestriction(userId){const user=publicUser(get('SELECT * FROM users WHERE id=?',[userId]));sendToUsers(null,{t:'USER_UPDATE',d:{user}});sendToUsers([userId],{t:'ACCOUNT_RESTRICTED',d:{action:user.banned?'banned':user.suspended_until?'suspended':'none',until:user.suspended_until||null}})}
router.post('/mod/users/:id/suspend',authMiddleware,requirePerm('suspend'),wrap((req,res)=>{const t=guardTarget(req);const hours=Math.min(Math.max(Number(req.body.hours)||1,1),24*365);run('UPDATE users SET suspended_until=?,banned=0 WHERE id=?',[Date.now()+hours*3600e3,t.id]);pushRestriction(t.id);res.json({ok:true})}))
router.post('/mod/users/:id/ban',authMiddleware,requirePerm('ban'),wrap((req,res)=>{const t=guardTarget(req);run('UPDATE users SET banned=1,suspended_until=NULL WHERE id=?',[t.id]);pushRestriction(t.id);res.json({ok:true})}))
router.post('/mod/users/:id/pardon',authMiddleware,requirePerm('suspend'),wrap((req,res)=>{const t=guardTarget(req);run('UPDATE users SET banned=0,suspended_until=NULL WHERE id=?',[t.id]);pushRestriction(t.id);res.json({ok:true})}))
export function channelById(id){return get('SELECT * FROM channels WHERE id=?',[id])}
export function canAccess(user,ch){if(!ch)return false;if(ch.guild_id)return !!get('SELECT 1 AS x FROM guild_members WHERE guild_id=? AND user_id=?',[ch.guild_id,user.id]);return !!get('SELECT 1 AS x FROM dm_recipients WHERE channel_id=? AND user_id=?',[ch.id,user.id])}
export function guildRole(userId,guildId){return get('SELECT role FROM guild_members WHERE guild_id=? AND user_id=?',[guildId,userId])?.role||null}
export function messageRow(m){if(!m)return null;let attachments=null;try{attachments=m.attachments?JSON.parse(m.attachments):null}catch{}return {...m,attachments}}

/* session + account */
router.get('/session',authMiddleware,wrap((req,res)=>{const token=req.cookies?.[COOKIE];const p=verify(token);res.json({user:publicUser(req.user),session_id:p?.sid||null})}))
router.get('/settings',authMiddleware,wrap((req,res)=>{let settings=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id]);if(!settings){run('INSERT INTO user_settings (user_id) VALUES (?)',[req.user.id]);settings=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id])}res.json({settings})}))
router.patch('/settings',authMiddleware,wrap((req,res)=>{const allowed={theme:['dark','light','system'],density:['cozy','compact'],reduced_motion:[0,1],desktop_notifications:[0,1],notification_sounds:[0,1],message_sounds:[0,1],dm_notifications:[0,1],mention_notifications:[0,1],friend_notifications:[0,1],show_activities:[0,1],autoplay_gifs:[0,1],developer_mode:[0,1],input_mode:['voice_activity','push_to_talk']};let cur=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id]);if(!cur)run('INSERT INTO user_settings (user_id) VALUES (?)',[req.user.id]);const keys=[];const vals=[];for(const [k,choices] of Object.entries(allowed)){if(req.body[k]===undefined)continue;const v=choices.includes(req.body[k])?req.body[k]:String(req.body[k]);if(!choices.map(String).includes(String(v)))throw httpError(400,`Некорректное значение: ${k}`);keys.push(`${k}=?`);vals.push(typeof choices[0]==='number'?Number(v):v)}if(keys.length)run(`UPDATE user_settings SET ${keys.join(',')} WHERE user_id=?`,[...vals,req.user.id]);res.json({settings:get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id])})}))
router.get('/blocks',authMiddleware,wrap((req,res)=>res.json({users:all('SELECT u.* FROM blocks b JOIN users u ON u.id=b.blocked_user_id WHERE b.user_id=? ORDER BY b.created_at DESC',req.user.id).map(publicUser)})))
router.post('/blocks/:userId',authMiddleware,wrap((req,res)=>{if(req.params.userId===req.user.id)throw httpError(400,'Нельзя заблокировать себя');if(!get('SELECT id FROM users WHERE id=?',req.params.userId))throw httpError(404,'Пользователь не найден');run('INSERT OR IGNORE INTO blocks (user_id,blocked_user_id,created_at) VALUES (?,?,?)',[req.user.id,req.params.userId,now()]);run('DELETE FROM friend_requests WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?)',[req.user.id,req.params.userId,req.params.userId,req.user.id]);run('DELETE FROM friendships WHERE (user_id=? AND friend_id=?) OR (user_id=? AND friend_id=?)',[req.user.id,req.params.userId,req.params.userId,req.user.id]);res.json({ok:true})}))
router.delete('/blocks/:userId',authMiddleware,wrap((req,res)=>{run('DELETE FROM blocks WHERE user_id=? AND blocked_user_id=?',[req.user.id,req.params.userId]);res.json({ok:true})}))

/* profile */
router.patch('/me',authMiddleware,wrap((req,res)=>{const fields=[];const vals=[];const allowed=['display_name','pronouns','banner_color','custom_status','status_icon','bio','avatar','status'];for(const k of allowed)if(req.body[k]!==undefined){let v=req.body[k];if(k==='display_name'||k==='pronouns'||k==='custom_status'||k==='status_icon'||k==='bio')v=String(v).slice(0,k==='bio'?190:64);if(k==='avatar'&&v!==null){v=String(v);if(v.length>1_500_000)throw httpError(400,'Аватар слишком большой')}if(k==='status'&&!['online','idle','dnd','invisible'].includes(v))throw httpError(400,'Некорректный статус');fields.push(`${k}=?`);vals.push(v)}if(req.body.username!==undefined){const u=String(req.body.username).trim();if(!/^[a-zA-Z0-9_.\u0430-\u044f\u0410-\u042fёЁ-]{2,32}$/.test(u))throw httpError(400,'Некорректное имя пользователя');if(get('SELECT id FROM users WHERE username=? COLLATE NOCASE AND id<>?',[u,req.user.id]))throw httpError(409,'Имя занято');fields.push('username=?');vals.push(u)}if(fields.length)run(`UPDATE users SET ${fields.join(',')} WHERE id=?`,[...vals,req.user.id]);res.json({user:publicUser(get('SELECT * FROM users WHERE id=?',[req.user.id]))})}))
router.put('/me/status',authMiddleware,wrap((req,res)=>{const status=String(req.body.status||'online');if(!['online','idle','dnd','invisible'].includes(status))throw httpError(400,'Некорректный статус');run('UPDATE users SET status=? WHERE id=?',[status,req.user.id]);res.json({status})}))
router.get('/badges',authMiddleware,wrap((req,res)=>res.json({badges:BADGES})))
router.get('/admin/users',authMiddleware,requireAdmin,wrap((req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();let users=all('SELECT * FROM users ORDER BY created_at ASC');if(q)users=users.filter(u=>u.username.toLowerCase().includes(q));res.json({users:users.slice(0,200).map(publicUser)})}))
router.put('/admin/users/:id/badges',authMiddleware,requireAdmin,wrap((req,res)=>{const target=get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!target)throw httpError(404,'Пользователь не найден');const ids=[...new Set((Array.isArray(req.body.badges)?req.body.badges:[]).map(String))];if(ids.length>25)throw httpError(400,'Слишком много бейджей');const unknown=ids.filter(id=>!BADGE_IDS.has(id));if(unknown.length)throw httpError(400,'Неизвестный бейдж: '+unknown.join(', '));run('UPDATE users SET badges=? WHERE id=?',[JSON.stringify(ids),target.id]);res.json({user:publicUser(get('SELECT * FROM users WHERE id=?',[target.id]))})}))

/* search with safe access filtering */
router.get('/search',authMiddleware,wrap((req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();if(q.length<2)return res.json({users:[],messages:[]});const users=all('SELECT * FROM users WHERE LOWER(username) LIKE ? LIMIT 10',[`%${q}%`]).map(publicUser);const ids=[...all('SELECT id FROM channels WHERE guild_id IN (SELECT guild_id FROM guild_members WHERE user_id=?)',[req.user.id]).map(c=>c.id),...all('SELECT channel_id FROM dm_recipients WHERE user_id=?',[req.user.id]).map(c=>c.channel_id)];if(!ids.length)return res.json({users,messages:[]});const msgs=all(`SELECT * FROM messages WHERE channel_id IN (${ids.map(()=>'?').join(',')}) AND LOWER(content) LIKE ? ORDER BY created_at DESC LIMIT 30`,[...ids,`%${q}%`]).map(messageRow);res.json({users,messages:msgs})}))
