import express from 'express'
import { get, all, run, uid, now } from './db.js'
import { register, login, sign, verify, authMiddleware, optionalAuthMiddleware, publicUser, httpError, COOKIE, restrictionOf } from './auth.js'
import { sendToUsers } from './hub.js'
import { presence, getStatus, voiceSnapshot, userVoiceChannel } from './state.js'
import { BADGES, BADGE_IDS, permsOf } from '../shared/badges.js'

export const router = express.Router()
const wrap = fn => (req,res,next) => { try { const r = fn(req,res,next); if (r && typeof r.catch === 'function') r.catch(next) } catch(e) { next(e) } }
function requireAdmin(req,res,next){if(!req.user.admin)return res.status(403).json({error:'Только для администраторов платформы'});next()}
export function userPerms(u){if(!u)return new Set();if(u.admin)return new Set(['suspend','ban','delete_any_message','grant_badges']);let ids=[];try{ids=u.badges?JSON.parse(u.badges):[]}catch{}return new Set(permsOf(Array.isArray(ids)?ids:[]))}
function requirePerm(perm){return(req,res,next)=>{if(!userPerms(req.user).has(perm))return res.status(403).json({error:'Недостаточно прав модерации'});next()}}
function guardTarget(req){const t=get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!t)throw httpError(404,'Пользователь не найден');if(t.id===req.user.id)throw httpError(400,'Нельзя применить ограничение к себе');if(t.admin&&!req.user.admin)throw httpError(403,'Нельзя модерировать администратора платформы');return t}
function pushRestriction(userId){const user=publicUser(get('SELECT * FROM users WHERE id=?',[userId]));sendToUsers(null,{t:'USER_UPDATE',d:{user}});sendToUsers([userId],{t:'ACCOUNT_RESTRICTED',d:{action:user.banned?'banned':user.suspended_until?'suspended':'none',until:user.suspended_until||null}})}
router.post('/mod/users/:id/suspend',authMiddleware,requirePerm('suspend'),wrap((req,res)=>{const t=guardTarget(req);const hours=Math.min(Math.max(Number(req.body.hours)||1,1),24*365);run('UPDATE users SET suspended_until=?,banned=0 WHERE id=?',[Date.now()+hours*3600e3,t.id]);pushRestriction(t.id);res.json({ok:true})}))
router.post('/mod/users/:id/ban',authMiddleware,requirePerm('ban'),wrap((req,res)=>{const t=guardTarget(req);run('UPDATE users SET banned=1,suspended_until=NULL WHERE id=?',[t.id]);pushRestriction(t.id);res.json({ok:true})}))
router.post('/mod/users/:id/pardon',authMiddleware,requirePerm('suspend'),wrap((req,res)=>{const t=guardTarget(req);run('UPDATE users SET banned=0,suspended_until=NULL WHERE id=?',[t.id]);pushRestriction(t.id);res.json({ok:true})}))
export function channelById(id){return get('SELECT * FROM channels WHERE id=?',[id])}
export function canAccess(user,ch){if(!ch)return false;if(ch.guild_id)return !!get('SELECT 1 AS x FROM guild_members WHERE guild_id=? AND user_id=?',[ch.guild_id,user.id]);return !!get('SELECT 1 AS x FROM dm_recipients WHERE channel_id=? AND user_id=?',[ch.id,user.id])}
export function guildRole(userId,guildId){return get('SELECT role FROM guild_members WHERE guild_id=? AND user_id=?',[guildId,userId])?.role||null}
export function messageRow(m){if(!m)return null;let attachments=null;try{attachments=m.attachments?JSON.parse(m.attachments):null}catch{}return {...m,attachments}}
function loadMessage(id){return messageRow(get('SELECT * FROM messages WHERE id=?',[id]))}
function reactionsFor(ids){if(!ids.length)return{};const out={};for(const r of all(`SELECT * FROM reactions WHERE message_id IN (${ids.map(()=>'?').join(',')})`,...ids)){out[r.message_id]=out[r.message_id]||[];out[r.message_id].push({emoji:r.emoji,user_id:r.user_id})}return out}
function serializeMessages(msgs){const rx=reactionsFor(msgs.map(m=>m.id));return msgs.map(m=>({...m,reactions:rx[m.id]||[]}))}
export function postSystemMessage(channelId,authorId,content){const ch=channelById(channelId);if(!ch)return;const id=uid(),ts=now();run('INSERT INTO messages (id,channel_id,author_id,content,created_at) VALUES (?,?,?,?,?)',[id,channelId,authorId,'[SYS]'+content,ts]);const message={id,channel_id:channelId,author_id:authorId,content:'[SYS]'+content,reply_to:null,attachments:null,pinned:0,created_at:ts,reactions:[]};const audience=ch.guild_id?all('SELECT user_id FROM guild_members WHERE guild_id=?',[ch.guild_id]).map(m=>m.user_id):all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[channelId]).map(m=>m.user_id);sendToUsers(audience,{t:'MESSAGE_CREATE',d:{message,channel_id:channelId}})}

router.post('/register',wrap((req,res)=>{const user=register(req.body.username,req.body.password);res.cookie(COOKIE,sign(user),{httpOnly:true,sameSite:'lax',maxAge:30*864e5});res.json({user:publicUser(user)})}))
router.post('/login',wrap((req,res)=>{const user=login(req.body.username,req.body.password);res.cookie(COOKIE,sign(user),{httpOnly:true,sameSite:'lax',maxAge:30*864e5});res.json({user:publicUser(user)})}))
router.post('/logout',(req,res)=>{res.clearCookie(COOKIE);res.json({ok:true})})
router.get('/me',optionalAuthMiddleware,wrap((req,res)=>res.json({user:publicUser(req.user)})))
router.patch('/me',authMiddleware,wrap((req,res)=>{const{username,bio,avatar,status,display_name,pronouns,banner_color,custom_status,status_icon}=req.body;if(username!==undefined){const u=String(username).trim();if(!/^[a-zA-Z0-9_.\u0430-\u044f\u0410-\u042fёЁ-]{2,32}$/.test(u))throw httpError(400,'Некорректное имя');const taken=get('SELECT id FROM users WHERE username=? COLLATE NOCASE AND id!=?',[u,req.user.id]);if(taken)throw httpError(409,'Имя занято');run('UPDATE users SET username=? WHERE id=?',[u,req.user.id])}if(display_name!==undefined)run('UPDATE users SET display_name=? WHERE id=?',[String(display_name).trim().slice(0,32)||null,req.user.id]);if(pronouns!==undefined)run('UPDATE users SET pronouns=? WHERE id=?',[String(pronouns).trim().slice(0,30)||null,req.user.id]);if(banner_color!==undefined){const c=String(banner_color).trim();if(c&&!/^#[0-9a-fA-F]{3,8}$/.test(c))throw httpError(400,'Некорректный цвет баннера');run('UPDATE users SET banner_color=? WHERE id=?',[c||null,req.user.id])}if(bio!==undefined)run('UPDATE users SET bio=? WHERE id=?',[String(bio).slice(0,190),req.user.id]);if(custom_status!==undefined)run('UPDATE users SET custom_status=? WHERE id=?',[String(custom_status).slice(0,80)||null,req.user.id]);if(status_icon!==undefined){const ICONS=['','🎮','📖','🎧'];if(!ICONS.includes(status_icon))throw httpError(400,'Некорректная иконка статуса');run('UPDATE users SET status_icon=? WHERE id=?',[status_icon||null,req.user.id])}if(avatar!==undefined){if(avatar&&String(avatar).length>1500000)throw httpError(400,'Аватар слишком большой');run('UPDATE users SET avatar=? WHERE id=?',[avatar||null,req.user.id])}if(status!==undefined){if(!['online','idle','dnd','invisible'].includes(status))throw httpError(400,'Статус некорректен');run('UPDATE users SET status=? WHERE id=?',[status,req.user.id]);const p=presence.get(req.user.id);if(p)p.status=status==='invisible'?'invisible':status}const user=get('SELECT * FROM users WHERE id=?',[req.user.id]);sendToUsers([req.user.id],{t:'ME_UPDATE',d:{user:publicUser(user)}});sendToUsers(null,{t:'USER_UPDATE',d:{user:publicUser(user)}});sendToUsers(null,{t:'PRESENCE',d:{user_id:user.id,status:getStatus(user.id)}});res.json({user:publicUser(user)})}))
router.post('/me/password',authMiddleware,wrap(async(req,res)=>{const bcrypt=(await import('bcryptjs')).default;const{current,next}=req.body;if(!bcrypt.compareSync(current||'',req.user.password_hash))throw httpError(401,'Текущий пароль неверен');if(!next||next.length<6)throw httpError(400,'Новый пароль слишком короткий');run('UPDATE users SET password_hash=? WHERE id=?',[bcrypt.hashSync(next,10),req.user.id]);res.json({ok:true})}))
const REQ_COLS='r.id AS rid,r.created_at AS rcreated,u.id AS uid,u.username AS uusername,u.discriminator AS udisc,u.avatar AS uavatar,u.bio AS ubio,u.status AS ustatus'
function reqRow(r){return{id:r.rid,created_at:r.rcreated,user:{id:r.uid,username:r.uusername,discriminator:r.udisc,avatar:r.uavatar,bio:r.ubio,status:r.ustatus}}}
router.get('/state',authMiddleware,wrap((req,res)=>{const me=req.user.id;const users=all('SELECT * FROM users').map(publicUser);const friends=all('SELECT u.* FROM friendships f JOIN users u ON u.id=f.friend_id WHERE f.user_id=?',me).map(publicUser);const incoming=all(`SELECT ${REQ_COLS} FROM friend_requests r JOIN users u ON u.id=r.from_user WHERE r.to_user=?`,me).map(reqRow);const outgoing=all(`SELECT ${REQ_COLS} FROM friend_requests r JOIN users u ON u.id=r.to_user WHERE r.from_user=?`,me).map(reqRow);const reads={};for(const r of all('SELECT * FROM reads WHERE user_id=?',me))reads[r.channel_id]=r.last_read;const dmChannels=all(`SELECT DISTINCT c.* FROM channels c JOIN dm_recipients d ON d.channel_id=c.id WHERE d.user_id=? AND c.type='dm'`,me).map(c=>{const recipients=all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[c.id]).map(r=>r.user_id);const last=get('SELECT * FROM messages WHERE channel_id=? ORDER BY CREATED_AT DESC LIMIT 1',[c.id]);const unread=get('SELECT COUNT(*) AS n FROM messages WHERE channel_id=? AND created_at>? AND author_id!=?',[c.id,reads[c.id]||0,me]).n;return{...c,recipients,last_message:last?messageRow(last):null,unread}}).sort((a,b)=>(b.last_message?.created_at||b.created_at)-(a.last_message?.created_at||a.created_at));const guilds=all(`SELECT g.*,gm.role AS my_role FROM guilds g JOIN guild_members gm ON gm.guild_id=g.id WHERE gm.user_id=?`,me).map(g=>{const channels=all('SELECT * FROM channels WHERE guild_id=? ORDER BY position,created_at',[g.id]).map(c=>{const last=get('SELECT * FROM messages WHERE channel_id=? ORDER BY created_at DESC LIMIT 1',[c.id]);const unread=get('SELECT COUNT(*) AS n FROM messages WHERE channel_id=? AND created_at>? AND author_id!=?',[c.id,reads[c.id]||0,me]).n;return{...c,last_message:last?{id:last.id,author_id:last.author_id,content:last.content.slice(0,80),created_at:last.created_at}:null,unread}});const members=all('SELECT user_id,role,joined_at FROM guild_members WHERE guild_id=?',[g.id]);return{...g,channels,members}});res.json({me:publicUser(req.user),users,friends,incoming,outgoing,dmChannels,guilds,reads,voice:voiceSnapshot(),presences:Object.fromEntries([...presence.entries()].map(([id,p])=>[id,p.status]))})}))
function friendsPayload(userId){return{friends:all('SELECT u.* FROM friendships f JOIN users u ON u.id=f.friend_id WHERE f.user_id=?',userId).map(publicUser),incoming:all(`SELECT ${REQ_COLS} FROM friend_requests r JOIN users u ON u.id=r.from_user WHERE r.to_user=?`,userId).map(reqRow),outgoing:all(`SELECT ${REQ_COLS} FROM friend_requests r JOIN users u ON u.id=r.to_user WHERE r.from_user=?`,userId).map(reqRow)}}
function pushFriends(a,b){for(const id of new Set([a,b]))sendToUsers([id],{t:'FRIENDS_UPDATE',d:friendsPayload(id)})}
router.post('/friends/request',authMiddleware,wrap((req,res)=>{const name=String(req.body.username||'').trim();const target=get('SELECT * FROM users WHERE username=? COLLATE NOCASE',[name]);if(!target)throw httpError(404,'Пользователь не найден');if(target.id===req.user.id)throw httpError(400,'Нельзя добавить себя');if(get('SELECT 1 AS x FROM friendships WHERE user_id=? AND friend_id=?',[req.user.id,target.id]))throw httpError(409,'Вы уже друзья');const mine=get('SELECT * FROM friend_requests WHERE from_user=? AND to_user=?',[req.user.id,target.id]);if(mine)throw httpError(409,'Заявка уже отправлена');const theirs=get('SELECT * FROM friend_requests WHERE from_user=? AND to_user=?',[target.id,req.user.id]);if(theirs){run('DELETE FROM friend_requests WHERE id=?',[theirs.id]);run('INSERT OR IGNORE INTO friendships (user_id,friend_id,created_at) VALUES (?,?,?)',[req.user.id,target.id,now()]);run('INSERT OR IGNORE INTO friendships (user_id,friend_id,created_at) VALUES (?,?,?)',[target.id,req.user.id,now()]);pushFriends(req.user.id,target.id);return res.json({accepted:true})}run('INSERT INTO friend_requests (id,from_user,to_user,created_at) VALUES (?,?,?,?)',[uid(),req.user.id,target.id,now()]);pushFriends(req.user.id,target.id);res.json({ok:true})}))
router.post('/friends/requests/:id/accept',authMiddleware,wrap((req,res)=>{const r=get('SELECT * FROM friend_requests WHERE id=? AND to_user=?',[req.params.id,req.user.id]);if(!r)throw httpError(404,'Заявка не найдена');run('DELETE FROM friend_requests WHERE id=?',[r.id]);run('INSERT OR IGNORE INTO friendships (user_id,friend_id,created_at) VALUES (?,?,?)',[req.user.id,r.from_user,now()]);run('INSERT OR IGNORE INTO friendships (user_id,friend_id,created_at) VALUES (?,?,?)',[r.from_user,req.user.id,now()]);pushFriends(req.user.id,r.from_user);res.json({ok:true})}))
router.delete('/friends/requests/:id',authMiddleware,wrap((req,res)=>{const r=get('SELECT * FROM friend_requests WHERE id=?',[req.params.id]);if(!r)throw httpError(404,'Заявка не найдена');if(r.from_user!==req.user.id&&r.to_user!==req.user.id)throw httpError(403,'Запрещено');run('DELETE FROM friend_requests WHERE id=?',[r.id]);pushFriends(r.from_user,r.to_user);res.json({ok:true})}))
router.delete('/friends/:id',authMiddleware,wrap((req,res)=>{run('DELETE FROM friendships WHERE user_id=? AND friend_id=?',[req.user.id,req.params.id]);run('DELETE FROM friendships WHERE user_id=? AND friend_id=?',[req.params.id,req.user.id]);pushFriends(req.user.id,req.params.id);res.json({ok:true})}))
router.post('/dm',authMiddleware,wrap((req,res)=>{const other=get('SELECT * FROM users WHERE id=?',[req.body.user_id]);if(!other)throw httpError(404,'Пользователь не найден');const existing=get(`SELECT c.* FROM channels c JOIN dm_recipients a ON a.channel_id=c.id AND a.user_id=? JOIN dm_recipients b ON b.channel_id=c.id AND b.user_id=? WHERE c.type='dm'`,[req.user.id,other.id]);if(existing)return res.json({channel:{...existing,recipients:all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[existing.id]).map(r=>r.user_id)},created:false});const id=uid();run('INSERT INTO channels (id,guild_id,type,name,position,created_at) VALUES (?,NULL,?,?,0,?)',[id,'dm',`${req.user.id}|${other.id}`,now()]);run('INSERT INTO dm_recipients (channel_id,user_id) VALUES (?,?)',[id,req.user.id]);run('INSERT INTO dm_recipients (channel_id,user_id) VALUES (?,?)',[id,other.id]);const channel={...channelById(id),recipients:[req.user.id,other.id]};sendToUsers([req.user.id,other.id],{t:'DM_CREATE',d:{channel}});res.json({channel,created:true})}))
router.delete('/dm/:id',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||ch.type!=='dm'||!canAccess(req.user,ch))throw httpError(404,'Не найдено');const others=all('SELECT user_id FROM dm_recipients WHERE channel_id=? AND user_id!=?',[ch.id,req.user.id]).map(r=>r.user_id);run('DELETE FROM reactions WHERE message_id IN (SELECT id FROM messages WHERE channel_id=?)',[ch.id]);run('DELETE FROM messages WHERE channel_id=?',[ch.id]);run('DELETE FROM reads WHERE channel_id=?',[ch.id]);run('DELETE FROM dm_recipients WHERE channel_id=?',[ch.id]);run('DELETE FROM channels WHERE id=?',[ch.id]);sendToUsers([req.user.id,...others],{t:'DM_REMOVE',d:{channel_id:ch.id}});res.json({ok:true})}))
function guildPayload(g){const channels=all('SELECT * FROM channels WHERE guild_id=? ORDER BY position,created_at',[g.id]);const members=all('SELECT user_id,role,joined_at FROM guild_members WHERE guild_id=?',[g.id]);return{...g,channels,members}}
export function pushGuild(guildId,extraUserIds=[]){const g=get('SELECT * FROM guilds WHERE id=?',[guildId]);if(!g)return;const memberIds=all('SELECT user_id FROM guild_members WHERE guild_id=?',[guildId]).map(m=>m.user_id);for(const id of new Set([...memberIds,...extraUserIds])){if(id===g.owner_id||memberIds.includes(id))sendToUsers([id],{t:'GUILD_UPDATE',d:{guild:guildPayload(g)}});else sendToUsers([id],{t:'GUILD_REMOVE',d:{guild_id:guildId}})}}
router.post('/guilds',authMiddleware,wrap((req,res)=>{const name=String(req.body.name||'').trim().slice(0,100);if(name.length<2)throw httpError(400,'Название слишком короткое');const id=uid();const colors=['#5865f2','#3ba55c','#faa61a','#ed4245','#eb459e','#9b59b6','#3498db'];const invite=Math.random().toString(36).slice(2,10);run('INSERT INTO guilds (id,name,owner_id,icon_color,invite_code,created_at) VALUES (?,?,?,?,?,?)',[id,name,req.user.id,colors[Math.floor(Math.random()*colors.length)],invite,now()]);run('INSERT INTO guild_members (guild_id,user_id,role,joined_at) VALUES (?,?,?,?)',[id,req.user.id,'owner',now()]);run('INSERT INTO channels (id,guild_id,type,name,position,created_at) VALUES (?,?,?,?,?,?)',[uid(),id,'text','general',0,now()]);run('INSERT INTO channels (id,guild_id,type,name,position,created_at) VALUES (?,?,?,?,?,?)',[uid(),id,'voice','General',1,now()]);pushGuild(id);res.json({guild:guildPayload(get('SELECT * FROM guilds WHERE id=?',[id]))})}))
router.post('/guilds/join',authMiddleware,wrap((req,res)=>{const code=String(req.body.code||'').trim();const g=get('SELECT * FROM guilds WHERE invite_code=?',[code]);if(!g)throw httpError(404,'Приглашение недействительно');if(get('SELECT 1 AS x FROM guild_members WHERE guild_id=? AND user_id=?',[g.id,req.user.id]))throw httpError(409,'Вы уже в этом сервере');run('INSERT INTO guild_members (guild_id,user_id,role,joined_at) VALUES (?,?,?,?)',[g.id,req.user.id,'member',now()]);pushGuild(g.id,[req.user.id]);res.json({guild:guildPayload(g)})}))
router.post('/guilds/:id/leave',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');if(g.owner_id===req.user.id)throw httpError(400,'Владелец не может выйти — удалите сервер');run('DELETE FROM guild_members WHERE guild_id=? AND user_id=?',[g.id,req.user.id]);pushGuild(g.id,[req.user.id]);res.json({ok:true})}))
router.patch('/guilds/:id',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');if(!['owner','admin'].includes(guildRole(req.user.id,g.id)))throw httpError(403,'Недостаточно прав');if(req.body.name)run('UPDATE guilds SET name=? WHERE id=?',[String(req.body.name).trim().slice(0,100),g.id]);if(req.body.icon_color)run('UPDATE guilds SET icon_color=? WHERE id=?',[String(req.body.icon_color).slice(0,20),g.id]);if(req.body.reset_invite)run('UPDATE guilds SET invite_code=? WHERE id=?',[Math.random().toString(36).slice(2,10),g.id]);pushGuild(g.id);res.json({guild:guildPayload(get('SELECT * FROM guilds WHERE id=?',[g.id]))})}))
router.delete('/guilds/:id',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');if(g.owner_id!==req.user.id)throw httpError(403,'Только владелец');const chIds=all('SELECT id FROM channels WHERE guild_id=?',[g.id]).map(c=>c.id);const memberIds=all('SELECT user_id FROM guild_members WHERE guild_id=?',[g.id]).map(m=>m.user_id);for(const c of chIds){run('DELETE FROM reactions WHERE message_id IN (SELECT id FROM messages WHERE channel_id=?)',[c]);run('DELETE FROM messages WHERE channel_id=?',[c]);run('DELETE FROM reads WHERE channel_id=?',[c])}run('DELETE FROM channels WHERE guild_id=?',[g.id]);run('DELETE FROM guild_members WHERE guild_id=?',[g.id]);run('DELETE FROM guilds WHERE id=?',[g.id]);sendToUsers(memberIds,{t:'GUILD_REMOVE',d:{guild_id:g.id}});res.json({ok:true})}))
router.post('/guilds/:id/members/:userId/role',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');if(guildRole(req.user.id,g.id)!=='owner')throw httpError(403,'Только владелец');if(req.params.userId===g.owner_id)throw httpError(400,'Нельзя изменить роль владельца');const role=['admin','member'].includes(req.body.role)?req.body.role:null;if(!role)throw httpError(400,'Роль некорректна');run('UPDATE guild_members SET role=? WHERE guild_id=? AND user_id=?',[role,g.id,req.params.userId]);pushGuild(g.id);res.json({ok:true})}))
router.delete('/guilds/:id/members/:userId',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');const my=guildRole(req.user.id,g.id),their=guildRole(req.params.userId,g.id);if(!my||my==='member')throw httpError(403,'Недостаточно прав');if(req.params.userId===g.owner_id)throw httpError(400,'Нельзя выгнать владельца');if(my==='admin'&&their==='admin')throw httpError(403,'Недостаточно прав');run('DELETE FROM guild_members WHERE guild_id=? AND user_id=?',[g.id,req.params.userId]);sendToUsers([req.params.userId],{t:'GUILD_REMOVE',d:{guild_id:g.id}});pushGuild(g.id);res.json({ok:true})}))
router.post('/guilds/:id/channels',authMiddleware,wrap((req,res)=>{const g=get('SELECT * FROM guilds WHERE id=?',[req.params.id]);if(!g)throw httpError(404,'Сервер не найден');if(!['owner','admin'].includes(guildRole(req.user.id,g.id)))throw httpError(403,'Недостаточно прав');const type=req.body.type==='voice'?'voice':'text';const name=String(req.body.name||'').trim().toLowerCase().replace(/\s+/g,'-').slice(0,40);if(!name)throw httpError(400,'Имя канала обязательно');const pos=(get('SELECT MAX(position) AS p FROM channels WHERE guild_id=?',[g.id]).p??-1)+1;const id=uid();run('INSERT INTO channels (id,guild_id,type,name,position,created_at) VALUES (?,?,?,?,?,?)',[id,g.id,type,name,pos,now()]);pushGuild(g.id);res.json({channel:channelById(id)})}))
router.patch('/channels/:id',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||!ch.guild_id)throw httpError(404,'Канал не найден');if(!['owner','admin'].includes(guildRole(req.user.id,ch.guild_id)))throw httpError(403,'Недостаточно прав');if(req.body.name){const name=String(req.body.name).trim().toLowerCase().replace(/\s+/g,'-').slice(0,40);if(name)run('UPDATE channels SET name=? WHERE id=?',[name,ch.id])}if(req.body.topic!==undefined)run('UPDATE channels SET topic=? WHERE id=?',[String(req.body.topic).slice(0,1024),ch.id]);if(req.body.position!==undefined)run('UPDATE channels SET position=? WHERE id=?',[Number(req.body.position)||0,ch.id]);pushGuild(ch.guild_id);res.json({channel:channelById(ch.id)})}))
router.delete('/channels/:id',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||!ch.guild_id)throw httpError(404,'Канал не найден');if(!['owner','admin'].includes(guildRole(req.user.id,ch.guild_id)))throw httpError(403,'Недостаточно прав');run('DELETE FROM reactions WHERE message_id IN (SELECT id FROM messages WHERE channel_id=?)',[ch.id]);run('DELETE FROM messages WHERE channel_id=?',[ch.id]);run('DELETE FROM reads WHERE channel_id=?',[ch.id]);run('DELETE FROM channels WHERE id=?',[ch.id]);pushGuild(ch.guild_id);res.json({ok:true})}))
router.get('/channels/:id/messages',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||!canAccess(req.user,ch))throw httpError(403,'Нет доступа');const limit=Math.min(Number(req.query.limit)||50,100);const before=Number(req.query.before)||now()+1;const msgs=all('SELECT * FROM messages WHERE channel_id=? AND created_at<? ORDER BY created_at DESC LIMIT ?',[ch.id,before,limit]).reverse();res.json({messages:serializeMessages(msgs),has_more:msgs.length===limit})}))
router.post('/channels/:id/messages',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||!canAccess(req.user,ch))throw httpError(403,'Нет доступа');let content=String(req.body.content??'').trim().replace(/^\[SYS\]/,'').slice(0,2000);let attachments=Array.isArray(req.body.attachments)?req.body.attachments.slice(0,4):[];attachments=attachments.filter(a=>a&&a.url&&a.name).map(a=>({name:String(a.name).slice(0,120),type:String(a.type||'').slice(0,60),size:Number(a.size)||0,url:String(a.url)}));const totalSize=attachments.reduce((s,a)=>s+a.url.length,0);if(totalSize>8000000)throw httpError(400,'Вложения слишком большие');if(!content&&!attachments.length)throw httpError(400,'Пустое сообщение');const reply_to=req.body.reply_to||null;const id=uid(),ts=now();run('INSERT INTO messages (id,channel_id,author_id,content,reply_to,attachments,created_at) VALUES (?,?,?,?,?,?,?)',[id,ch.id,req.user.id,content,reply_to,attachments.length?JSON.stringify(attachments):null,ts]);run('INSERT OR REPLACE INTO reads (user_id,channel_id,last_read) VALUES (?,?,?)',[req.user.id,ch.id,ts]);const message={...loadMessage(id),reactions:[]};const audience=ch.guild_id?all('SELECT user_id FROM guild_members WHERE guild_id=?',[ch.guild_id]).map(m=>m.user_id):all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[ch.id]).map(m=>m.user_id);sendToUsers(audience,{t:'MESSAGE_CREATE',d:{message,channel_id:ch.id}});res.json({message})}))
router.patch('/messages/:id',authMiddleware,wrap((req,res)=>{const m=get('SELECT * FROM messages WHERE id=?',[req.params.id]);if(!m)throw httpError(404,'Сообщение не найдено');if(m.author_id!==req.user.id)throw httpError(403,'Только автор');const content=String(req.body.content??'').trim().slice(0,2000);run('UPDATE messages SET content=?,edited_at=? WHERE id=?',[content,now(),m.id]);const ch=channelById(m.channel_id);const audience=ch.guild_id?all('SELECT user_id FROM guild_members WHERE guild_id=?',[ch.guild_id]).map(x=>x.user_id):all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[ch.id]).map(x=>x.user_id);sendToUsers(audience,{t:'MESSAGE_UPDATE',d:{message:loadMessage(m.id)}});res.json({message:loadMessage(m.id)})}))
router.delete('/messages/:id',authMiddleware,wrap((req,res)=>{const m=get('SELECT * FROM messages WHERE id=?',[req.params.id]);if(!m)throw httpError(404,'Сообщение не найдено');const ch=channelById(m.channel_id);const isMod=ch?.guild_id&&['owner','admin'].includes(guildRole(req.user.id,ch.guild_id));const isPlatformMod=userPerms(req.user).has('delete_any_message');if(m.author_id!==req.user.id&&!isMod&&!isPlatformMod)throw httpError(403,'Только автор или модератор');run('DELETE FROM reactions WHERE message_id=?',[m.id]);run('DELETE FROM messages WHERE id=?',[m.id]);const audience=ch.guild_id?all('SELECT user_id FROM guild_members WHERE guild_id=?',[ch.guild_id]).map(x=>x.user_id):all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[ch.id]).map(x=>x.user_id);sendToUsers(audience,{t:'MESSAGE_DELETE',d:{id:m.id,channel_id:m.channel_id}});res.json({ok:true})}))
router.post('/messages/:id/reactions',authMiddleware,wrap((req,res)=>{const m=get('SELECT * FROM messages WHERE id=?',[req.params.id]);if(!m)throw httpError(404,'Сообщение не найдено');const ch=channelById(m.channel_id);if(!canAccess(req.user,ch))throw httpError(403,'Нет доступа');const emoji=String(req.body.emoji||'').slice(0,16);if(!emoji)throw httpError(400,'Пустой эмодзи');const existing=get('SELECT 1 AS x FROM reactions WHERE message_id=? AND user_id=? AND emoji=?',[m.id,req.user.id,emoji]);if(existing)run('DELETE FROM reactions WHERE message_id=? AND user_id=? AND emoji=?',[m.id,req.user.id,emoji]);else run('INSERT INTO reactions (message_id,user_id,emoji,created_at) VALUES (?,?,?,?)',[m.id,req.user.id,emoji,now()]);const audience=ch.guild_id?all('SELECT user_id FROM guild_members WHERE guild_id=?',[ch.guild_id]).map(x=>x.user_id):all('SELECT user_id FROM dm_recipients WHERE channel_id=?',[ch.id]).map(x=>x.user_id);sendToUsers(audience,{t:'REACTION',d:{message_id:m.id,channel_id:ch.id,emoji,user_id:req.user.id,remove:!!existing}});res.json({ok:true})}))
router.post('/channels/:id/read',authMiddleware,wrap((req,res)=>{const ch=channelById(req.params.id);if(!ch||!canAccess(req.user,ch))throw httpError(403,'Нет доступа');run('INSERT OR REPLACE INTO reads (user_id,channel_id,last_read) VALUES (?,?,?)',[req.user.id,ch.id,now()]);res.json({ok:true})}))
router.get('/users/:id',authMiddleware,wrap((req,res)=>{const u=get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!u)throw httpError(404,'Пользователь не найден');const me=req.user.id;const isFriend=!!get('SELECT 1 AS x FROM friendships WHERE user_id=? AND friend_id=?',[me,u.id]);const inReq=get('SELECT * FROM friend_requests WHERE from_user=? AND to_user=?',[u.id,me]);const outReq=get('SELECT * FROM friend_requests WHERE from_user=? AND to_user=?',[me,u.id]);const mutualGuilds=all(`SELECT g.id,g.name,g.icon_color,ga.role AS my_role,gb.role AS their_role FROM guilds g JOIN guild_members ga ON ga.guild_id=g.id AND ga.user_id=? JOIN guild_members gb ON gb.guild_id=g.id AND gb.user_id=?`,[me,u.id]);const mutualFriends=all(`SELECT u2.id,u2.username,u2.display_name,u2.avatar FROM friendships f1 JOIN friendships f2 ON f2.user_id=f1.friend_id AND f2.friend_id=? JOIN users u2 ON u2.id=f1.friend_id WHERE f1.user_id=?`,[u.id,me]).map(x=>({...publicUser(x),presence:getStatus(x.id)}));const friendRow=get('SELECT created_at FROM friendships WHERE user_id=? AND friend_id=?',[me,u.id]);const note=get('SELECT note FROM user_notes WHERE owner_id=? AND user_id=?',[me,u.id]);res.json({user:publicUser(u),presence:getStatus(u.id),relationship:isFriend?'friend':inReq?'incoming':outReq?'outgoing':'none',voice_channel:userVoiceChannel(u.id),friend_since:friendRow?.created_at||null,mutual_guilds:mutualGuilds,mutual_friends:mutualFriends,note:note?.note||''})}))
router.put('/users/:id/note',authMiddleware,wrap((req,res)=>{run('INSERT OR REPLACE INTO user_notes (owner_id,user_id,note) VALUES (?,?,?)',[req.user.id,req.params.id,String(req.body.note||'').slice(0,190)]);res.json({ok:true})}))
router.get('/badges',authMiddleware,wrap((req,res)=>res.json({badges:BADGES})))
router.get('/admin/users',authMiddleware,requireAdmin,wrap((req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();let users=all('SELECT * FROM users ORDER BY created_at ASC');if(q)users=users.filter(u=>u.username.toLowerCase().includes(q));res.json({users:users.slice(0,200).map(publicUser)})}))
router.put('/admin/users/:id/badges',authMiddleware,requireAdmin,wrap((req,res)=>{const target=get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!target)throw httpError(404,'Пользователь не найден');const ids=[...new Set((Array.isArray(req.body.badges)?req.body.badges:[]).map(String))];if(ids.length>25)throw httpError(400,'Слишком много бейджей');const unknown=ids.filter(id=>!BADGE_IDS.has(id));if(unknown.length)throw httpError(400,'Неизвестный бейдж: '+unknown.join(', '));run('UPDATE users SET badges=? WHERE id=?',[JSON.stringify(ids),target.id]);const user=publicUser(get('SELECT * FROM users WHERE id=?',[target.id]));sendToUsers(null,{t:'USER_UPDATE',d:{user}});sendToUsers([target.id],{t:'ME_UPDATE',d:{user}});res.json({user})}))
router.get('/search',authMiddleware,wrap((req,res)=>{const q=String(req.query.q||'').trim().toLowerCase();if(q.length<2)return res.json({users:[],messages:[]});const users=all('SELECT * FROM users WHERE LOWER(username) LIKE ? LIMIT 10',[`%${q}%`]).map(publicUser);const ids=[...all('SELECT id FROM channels WHERE guild_id IN (SELECT guild_id FROM guild_members WHERE user_id=?)',[req.user.id]).map(c=>c.id),...all('SELECT channel_id FROM dm_recipients WHERE user_id=?',[req.user.id]).map(c=>c.channel_id)];if(!ids.length)return res.json({users,messages:[]});const msgs=all(`SELECT * FROM messages WHERE channel_id IN (${ids.map(()=>'?').join(',')}) AND LOWER(content) LIKE ? ORDER BY created_at DESC LIMIT 30`,[...ids,`%${q}%`]).map(messageRow);res.json({users,messages:msgs})}))

router.get('/session',authMiddleware,wrap((req,res)=>{const token=req.cookies?.[COOKIE];const p=verify(token);res.json({user:publicUser(req.user),session_id:p?.sid||null})}))
router.get('/settings',authMiddleware,wrap((req,res)=>{let settings=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id]);if(!settings){run('INSERT INTO user_settings(user_id) VALUES(?)',[req.user.id]);settings=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id])}res.json({settings})}))
router.patch('/settings',authMiddleware,wrap((req,res)=>{const allowed={theme:['dark','light','system'],density:['cozy','compact'],reduced_motion:[0,1],desktop_notifications:[0,1],notification_sounds:[0,1],message_sounds:[0,1],dm_notifications:[0,1],mention_notifications:[0,1],friend_notifications:[0,1],show_activities:[0,1],autoplay_gifs:[0,1],developer_mode:[0,1],input_mode:['voice_activity','push_to_talk']};let cur=get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id]);if(!cur)run('INSERT INTO user_settings(user_id) VALUES(?)',[req.user.id]);const keys=[];const vals=[];for(const[k,choices]of Object.entries(allowed)){if(req.body[k]===undefined)continue;const v=choices.includes(req.body[k])?req.body[k]:String(req.body[k]);if(!choices.map(String).includes(String(v)))throw httpError(400,'Некорректное значение: '+k);keys.push(`${k}=?`);vals.push(typeof choices[0]==='number'?Number(v):v)}if(keys.length)run(`UPDATE user_settings SET ${keys.join(',')} WHERE user_id=?`,[...vals,req.user.id]);res.json({settings:get('SELECT * FROM user_settings WHERE user_id=?',[req.user.id])})}))
router.get('/blocks',authMiddleware,wrap((req,res)=>res.json({users:all('SELECT u.* FROM blocks b JOIN users u ON u.id=b.blocked_user_id WHERE b.user_id=? ORDER BY b.created_at DESC',[req.user.id]).map(publicUser)})))
router.post('/blocks/:userId',authMiddleware,wrap((req,res)=>{if(req.params.userId===req.user.id)throw httpError(400,'Нельзя заблокировать себя');if(!get('SELECT id FROM users WHERE id=?',[req.params.userId]))throw httpError(404,'Пользователь не найден');run('INSERT OR IGNORE INTO blocks(user_id,blocked_user_id,created_at) VALUES(?,?,?)',[req.user.id,req.params.userId,now()]);run('DELETE FROM friend_requests WHERE (from_user=? AND to_user=?) OR (from_user=? AND to_user=?)',[req.user.id,req.params.userId,req.params.userId,req.user.id]);run('DELETE FROM friendships WHERE (user_id=? AND friend_id=?) OR (user_id=? AND friend_id=?)',[req.user.id,req.params.userId,req.params.userId,req.user.id]);res.json({ok:true})}))
router.delete('/blocks/:userId',authMiddleware,wrap((req,res)=>{run('DELETE FROM blocks WHERE user_id=? AND blocked_user_id=?',[req.user.id,req.params.userId]);res.json({ok:true})}))
