import React, { useEffect, useState } from 'react'
import { setUI } from '../lib/store.js'
import { api } from '../lib/api.js'
import { useStore } from '../lib/util.js'
import { IconX, IconUser, IconGear, IconMic, IconPalette, IconPeople } from './Icons.jsx'
import './AdvancedSettings.css'

const groups=[['АККАУНТ',[['profile','Мой аккаунт',IconUser],['privacy','Конфиденциальность',IconPeople]]],['ПРИЛОЖЕНИЕ',[['appearance','Внешний вид',IconPalette],['notifications','Уведомления',IconGear],['accessibility','Доступность',IconGear],['keybinds','Горячие клавиши',IconGear]]],['ГОЛОС И ВИДЕО',[['voice','Голос и видео',IconMic]]],['БЕЗОПАСНОСТЬ',[['security','Безопасность',IconGear]]]]
const defaults={theme:'dark',density:'cozy',fontSize:'15',reducedMotion:false,highContrast:false,desktop:true,sounds:true,mentions:true,dms:true,friendRequests:true,ptt:false,echo:true,noise:true}
function getPrefs(){try{return {...defaults,...JSON.parse(localStorage.getItem('dsh_preferences')||'{}')}}catch{return defaults}}
function savePrefs(p){localStorage.setItem('dsh_preferences',JSON.stringify(p))}
export default function AdvancedSettings(){const s=useStore();const me=s.me;const [tab,setTab]=useState('profile');const [p,setP]=useState(getPrefs);const patch=x=>{const n={...p,...x};setP(n);savePrefs(n);document.body.dataset.density=n.density;document.body.dataset.font=n.fontSize;document.body.classList.toggle('reduced-motion',n.reducedMotion);document.body.classList.toggle('high-contrast',n.highContrast)};useEffect(()=>{patch({})},[]);return <div className="advanced-settings"><aside className="as-nav"><div className="as-profile"><div className="as-avatar">{(me.username||'?')[0].toUpperCase()}</div><div><b>{me.display_name||me.username}</b><span>@{me.username}</span></div></div>{groups.map(([title,items])=><div key={title}><div className="as-group">{title}</div>{items.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={17}/>{label}</button>)}</div>)}<div className="as-spacer"/><button className="as-close" onClick={()=>setUI({settingsOpen:false})}>Выйти из настроек</button></aside><main className="as-main"><header><div><h1>{groups.flatMap(x=>x[1]).find(x=>x[0]===tab)?.[1]||'Настройки'}</h1><span>Персональные настройки аккаунта</span></div><button className="icon-btn" onClick={()=>setUI({settingsOpen:false})}><IconX size={20}/></button></header>{tab==='profile'&&<Profile me={me}/>} {tab==='privacy'&&<Privacy p={p} patch={patch}/>} {tab==='appearance'&&<Appearance p={p} patch={patch}/>} {tab==='notifications'&&<Notifications p={p} patch={patch}/>} {tab==='accessibility'&&<Accessibility p={p} patch={patch}/>} {tab==='keybinds'&&<Keybinds/>} {tab==='voice'&&<Voice p={p} patch={patch}/>} {tab==='security'&&<Security/>}</main></div>}
function Section({title,desc,children}){return <section className="as-section"><h2>{title}</h2>{desc&&<p>{desc}</p>}{children}</section>}
function Row({title,desc,children}){return <div className="as-row"><div><b>{title}</b>{desc&&<span>{desc}</span>}</div>{children}</div>}
function Toggle({value,onChange}){return <label className="as-toggle"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><i/></label>}
function Profile({me}){const [name,setName]=useState(me.display_name||'');const [bio,setBio]=useState(me.bio||'');const [msg,setMsg]=useState('');const save=async()=>{try{await api('/me',{method:'PATCH',body:{display_name:name,bio}});setMsg('Изменения сохранены')}catch(e){setMsg(e.message)}};return <><Section title="Профиль" desc="Настрой, как тебя видят другие пользователи."><div className="as-profile-card"><div className="as-big-avatar">{(name||me.username||'?')[0].toUpperCase()}</div><div><h3>{name||me.username}</h3><span>@{me.username}</span></div></div><label className="as-field">Отображаемое имя<input value={name} maxLength={32} onChange={e=>setName(e.target.value)}/></label><label className="as-field">Обо мне<textarea value={bio||''} maxLength={190} onChange={e=>setBio(e.target.value)}/></label><button className="btn primary" onClick={save}>Сохранить</button>{msg&&<small className="as-msg">{msg}</small>}</Section></>}
function Privacy({p,patch}){return <Section title="Конфиденциальность" desc="Контролируй, кто может взаимодействовать с тобой."><Row title="Личные сообщения" desc="Разрешать сообщения от участников общих серверов"><Toggle value={p.dms} onChange={v=>patch({dms:v})}/></Row><Row title="Запросы дружбы" desc="Разрешать другим отправлять запросы дружбы"><Toggle value={p.friendRequests} onChange={v=>patch({friendRequests:v})}/></Row><Row title="Уведомления об упоминаниях" desc="Показывать уведомления, когда тебя упоминают"><Toggle value={p.mentions} onChange={v=>patch({mentions:v})}/></Row></Section>}
function Appearance({p,patch}){return <><Section title="Тема" desc="Выбери оформление приложения."><div className="as-cards">{[['dark','Тёмная'],['light','Светлая'],['system','Системная']].map(([v,l])=><button className={p.theme===v?'selected':''} key={v} onClick={()=>patch({theme:v})}><span className={'theme-'+v}/><b>{l}</b></button>)}</div></Section><Section title="Плотность" desc="Количество пространства между элементами."><div className="as-segment">{[['cozy','Уютная'],['compact','Компактная']].map(([v,l])=><button className={p.density===v?'active':''} key={v} onClick={()=>patch({density:v})}>{l}</button>)}</div></Section><Section title="Размер текста"><select value={p.fontSize} onChange={e=>patch({fontSize:e.target.value})}><option value="13">Маленький</option><option value="15">Обычный</option><option value="17">Большой</option><option value="19">Очень большой</option></select></Section></>}
function Notifications({p,patch}){return <Section title="Уведомления" desc="Выбери, что должно тебя отвлекать."><Row title="Рабочий стол" desc="Показывать системные уведомления"><Toggle value={p.desktop} onChange={v=>patch({desktop:v})}/></Row><Row title="Звуки" desc="Звуки сообщений и событий"><Toggle value={p.sounds} onChange={v=>patch({sounds:v})}/></Row><Row title="Личные сообщения" desc="Уведомлять о новых сообщениях"><Toggle value={p.dms} onChange={v=>patch({dms:v})}/></Row><Row title="Упоминания" desc="Уведомлять о прямых упоминаниях"><Toggle value={p.mentions} onChange={v=>patch({mentions:v})}/></Row></Section>}
function Accessibility({p,patch}){return <Section title="Доступность" desc="Настройки интерфейса для более комфортной работы."><Row title="Уменьшить анимации" desc="Отключает большинство переходов и анимаций"><Toggle value={p.reducedMotion} onChange={v=>patch({reducedMotion:v})}/></Row><Row title="Высокая контрастность" desc="Увеличивает контраст текста и элементов"><Toggle value={p.highContrast} onChange={v=>patch({highContrast:v})}/></Row></Section>}
function Keybinds(){return <Section title="Горячие клавиши" desc="Быстрые команды приложения."><div className="as-key"><kbd>Ctrl</kbd><kbd>K</kbd><span>Поиск</span></div><div className="as-key"><kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>M</kbd><span>Включить / выключить микрофон</span></div><div className="as-key"><kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>D</kbd><span>Открыть личные сообщения</span></div><div className="as-key"><kbd>Esc</kbd><span>Закрыть окно</span></div></Section>}
function Voice({p,patch}){return <Section title="Голос и видео" desc="Настройки устройств и обработки голоса."><Row title="Push-to-talk" desc="Передача голоса только при удержании клавиши"><Toggle value={p.ptt} onChange={v=>patch({ptt:v})}/></Row><Row title="Подавление эха" desc="Уменьшать эхо микрофона"><Toggle value={p.echo} onChange={v=>patch({echo:v})}/></Row><Row title="Шумоподавление" desc="Фильтровать постоянный фоновый шум"><Toggle value={p.noise} onChange={v=>patch({noise:v})}/></Row></Section>}
function Security(){const logout=async()=>{await api('/logout',{method:'POST'});location.reload()};return <Section title="Безопасность" desc="Управление доступом к аккаунту."><div className="as-security"><b>Сессия браузера</b><span>Текущая активная сессия</span><button className="btn ghost" onClick={logout}>Выйти из аккаунта</button></div><div className="as-security"><b>Смена пароля</b><span>Используй раздел безопасности для смены пароля.</span></div></Section>}
