import React, { useEffect, useMemo, useState } from 'react'
import { Modal, Avatar, confirmDialog } from './Common.jsx'
import { api } from '../lib/api.js'
import { getState, setUI, upsertGuild, displayName } from '../lib/store.js'
import { IconX, IconHash, IconSpeaker, IconShield, IconUsers, IconCrown, IconTrash, IconCopy, IconPlus, IconCheck, IconBadge } from './Icons.jsx'
import { useStore } from '../lib/util.js'

const PERMS = ['VIEW_CHANNEL','SEND_MESSAGES','MANAGE_MESSAGES','MANAGE_CHANNELS','MANAGE_SERVER','MANAGE_ROLES','MANAGE_WEBHOOKS','MANAGE_EMOJIS','KICK_MEMBERS','BAN_MEMBERS','MODERATE_MEMBERS','MENTION_EVERYONE','ATTACH_FILES','EMBED_LINKS','CONNECT','SPEAK','MUTE_MEMBERS','DEAFEN_MEMBERS','MOVE_MEMBERS','STREAM','ADMINISTRATOR']
const PERM_LABELS = { VIEW_CHANNEL:'Просмотр каналов', SEND_MESSAGES:'Отправка сообщений', MANAGE_MESSAGES:'Управление сообщениями', MANAGE_CHANNELS:'Управление каналами', MANAGE_SERVER:'Управление сервером', MANAGE_ROLES:'Управление ролями', MANAGE_WEBHOOKS:'Управление вебхуками', MANAGE_EMOJIS:'Управление эмодзи', KICK_MEMBERS:'Выгонять участников', BAN_MEMBERS:'Банить участников', MODERATE_MEMBERS:'Модерация участников', MENTION_EVERYONE:'@everyone и @here', ATTACH_FILES:'Прикреплять файлы', EMBED_LINKS:'Встраиваемые ссылки', CONNECT:'Подключение к голосу', SPEAK:'Говорить', MUTE_MEMBERS:'Отключать микрофоны', DEAFEN_MEMBERS:'Отключать звук', MOVE_MEMBERS:'Перемещать участников', STREAM:'Стрим', ADMINISTRATOR:'Администратор' }
const TABS = [
  ['overview','Обзор'], ['roles','Роли'], ['members','Участники'], ['channels','Каналы'], ['invites','Приглашения'], ['bans','Баны'], ['automod','AutoMod'], ['audit','Журнал аудита'], ['integrations','Интеграции']
]

export default function ServerSettings({ guildId, onClose }) {
  const s = useStore(); const guild = s.guilds.find(x => x.id === guildId)
  const [tab, setTab] = useState('overview')
  if (!guild) return null
  const member = guild.members?.find(m => m.user_id === s.me.id)
  const role = member?.role || guild.my_role
  const canManage = role === 'owner' || role === 'admin'
  const isOwner = role === 'owner'
  const body = { overview:<Overview guild={guild} canManage={canManage} onClose={onClose}/>, roles:<Roles guild={guild} canManage={canManage}/>, members:<Members guild={guild} canManage={canManage} isOwner={isOwner}/>, channels:<Channels guild={guild} canManage={canManage}/>, invites:<Invites guild={guild} canManage={canManage}/>, bans:<Bans guild={guild} canManage={canManage}/>, automod:<AutoMod guild={guild} canManage={canManage}/>, audit:<Audit guild={guild} canManage={canManage}/>, integrations:<Integrations guild={guild} canManage={canManage}/> }[tab]
  return <Modal onClose={onClose} width={980} className="server-settings-pro">
    <div className="ss-layout">
      <aside className="ss-nav">
        <div className="ss-server"><div className="ss-server-icon" style={{background:guild.icon_color||'var(--brand)'}}>{abbr(guild.name)}</div><div><b>{guild.name}</b><span>Настройки сервера</span></div></div>
        <div className="ss-nav-scroll">{TABS.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}<div className="ss-divider"/><button className="danger" onClick={()=>setUI({modal:null})}>Закрыть</button></div>
      </aside>
      <main className="ss-content"><div className="ss-content-head"><div><h2>{TABS.find(x=>x[0]===tab)?.[1]}</h2><p>{guild.name}</p></div><button className="icon-btn" onClick={onClose}><IconX size={20}/></button></div>{body}</main>
    </div>
  </Modal>
}

function Section({title,desc,children}){return <section className="ss-section"><div className="ss-section-title">{title}</div>{desc&&<div className="ss-desc">{desc}</div>}{children}</section>}
function Button({children,...p}){return <button className="btn primary" {...p}>{children}</button>}
function Input({label,children,...p}){return <label className="ss-field"><span>{label}</span><input className="field-input" {...p}/>{children}</label>}
function abbr(n){return String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function refreshGuild(id){ const st=getState(); const g=st.guilds.find(x=>x.id===id); if(g) upsertGuild({...g}) }

function Overview({guild,canManage,onClose}){
 const [name,setName]=useState(guild.name); const [color,setColor]=useState(guild.icon_color||'#5865f2'); const [code,setCode]=useState(guild.invite_code); const [saved,setSaved]=useState(false); const [err,setErr]=useState('')
 const save=async()=>{try{const r=await api(`/guilds/${guild.id}`,{method:'PATCH',body:{name,icon_color:color}}); if(r.guild)upsertGuild(r.guild);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){setErr(e.message)}}
 const reset=async()=>{try{const r=await api(`/guilds/${guild.id}`,{method:'PATCH',body:{reset_invite:true}});setCode(r.guild?.invite_code||code)}catch(e){setErr(e.message)}}
 return <><Section title="Профиль сервера" desc="Название и оформление, которые видят участники."><div className="ss-preview"><div className="ss-big-icon" style={{background:color}}>{abbr(name)}</div><div><h3>{name}</h3><span>{guild.members?.length||0} участников · {guild.channels?.length||0} каналов</span></div></div><Input label="Название" value={name} disabled={!canManage} onChange={e=>setName(e.target.value)}/><div className="ss-label">Цвет сервера</div><div className="ss-colors">{['#5865f2','#3ba55c','#faa61a','#ed4245','#eb459e','#9b59b6','#3498db','#1abc9c','#1e1f22'].map(c=><button key={c} disabled={!canManage} className={color===c?'selected':''} style={{background:c}} onClick={()=>setColor(c)}/>)}</div><div className="ss-actions">{saved&&<span className="ss-ok"><IconCheck size={16}/> Сохранено</span>}{err&&<span className="ss-error">{err}</span>}{canManage&&<Button onClick={save}>Сохранить изменения</Button>}</div></Section><Section title="Приглашение" desc="Основной код приглашения сервера."><div className="ss-invite"><code>{code}</code><button className="btn ghost" onClick={()=>navigator.clipboard?.writeText(code)}><IconCopy size={17}/> Копировать</button>{canManage&&<button className="btn ghost" onClick={reset}>Обновить код</button>}</div></Section><Section title="Безопасность" desc="Критические действия требуют подтверждения."><div className="ss-danger-card"><div><b>Удалить сервер</b><span>Все каналы и данные сервера будут удалены.</span></div>{guild.owner_id===getState().me.id&&<button className="btn red" onClick={()=>confirmDialog({title:'Удалить сервер?',body:`Удалить «${guild.name}» без возможности восстановления?`,okLabel:'Удалить',danger:true,onOk:async()=>{await api(`/guilds/${guild.id}`,{method:'DELETE'});onClose();setUI({guildId:'@home',channelId:null})}})}>Удалить сервер</button>}</div></Section></>}

function Roles({guild,canManage}){const [roles,setRoles]=useState([]);const [editing,setEditing]=useState(null);const [loading,setLoading]=useState(true);const load=()=>api(`/guilds/${guild.id}/roles`).then(r=>setRoles(r.roles||[])).catch(()=>setRoles([])).finally(()=>setLoading(false));useEffect(()=>{load()},[guild.id]);const create=async()=>{try{await api(`/guilds/${guild.id}/roles`,{body:{name:'Новая роль',permissions:['VIEW_CHANNEL','SEND_MESSAGES']}});load()}catch(e){alert(e.message)}};const save=async r=>{try{await api(`/guilds/${guild.id}/roles/${r.id}`,{method:'PATCH',body:{name:r.name,color:r.color,permissions:r.permissions,mentionable:r.mentionable}});setEditing(null);load()}catch(e){alert(e.message)}};const del=async r=>confirmDialog({title:`Удалить роль «${r.name}»?`,okLabel:'Удалить',danger:true,onOk:async()=>{try{await api(`/guilds/${guild.id}/roles/${r.id}`,{method:'DELETE'});load()}catch(e){alert(e.message)}}});return <><Section title="Роли" desc="Роли определяют права участников и порядок доступа."><div className="ss-toolbar"><span>{roles.length} ролей</span>{canManage&&<Button onClick={create}><IconPlus size={17}/> Создать роль</Button>}</div>{loading?<div className="ss-empty">Загрузка…</div>:roles.map(r=><div className="ss-role" key={r.id}><span className="ss-role-dot" style={{background:r.color||'var(--text-muted)'}}/><div className="ss-role-main">{editing?.id===r.id?<input className="field-input" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/>:<b>{r.name}</b>}<small>{(r.permissions||[]).length} разрешений {r.mentionable?'· упоминаемая':''}</small></div>{canManage&&<><button className="btn ghost small" onClick={()=>setEditing({...r})}>{editing?.id===r.id?'Отмена':'Изменить'}</button>{editing?.id===r.id&&<button className="btn green small" onClick={()=>save(editing)}>Сохранить</button>}<button className="icon-btn danger" onClick={()=>del(r)}><IconTrash size={17}/></button></>}</div>)}</Section>{editing&&<RoleEditor role={editing} onChange={setEditing}/>}</>}
function RoleEditor({role,onChange}){return <Section title={`Разрешения: ${role.name}`} desc="Выбери разрешения роли."><div className="ss-perms">{PERMS.map(p=><label key={p} className="ss-check"><input type="checkbox" checked={(role.permissions||[]).includes(p)} onChange={e=>onChange({...role,permissions:e.target.checked?[...new Set([...(role.permissions||[]),p])]:role.permissions.filter(x=>x!==p)})}/><span><b>{PERM_LABELS[p]}</b><small>{p}</small></span></label>)}</div></Section>}

function Members({guild,canManage,isOwner}){const s=useStore();const [query,setQuery]=useState('');const [busy,setBusy]=useState(null);const members=(guild.members||[]).filter(m=>{const u=s.users[m.user_id];return !query||u?.username?.toLowerCase().includes(query.toLowerCase())||u?.display_name?.toLowerCase().includes(query.toLowerCase())});const act=async(id,fn)=>{setBusy(id);try{await fn();refreshGuild(guild.id)}catch(e){alert(e.message)}finally{setBusy(null)}};return <Section title="Участники" desc={`${guild.members?.length||0} участников на сервере.`}><input className="field-input" placeholder="Поиск участников" value={query} onChange={e=>setQuery(e.target.value)}/><div className="ss-list">{members.map(m=>{const u=s.users[m.user_id];if(!u)return null;const owner=m.role==='owner';return <div className="ss-member" key={m.user_id}><Avatar user={u} size={40} showStatus/><div className="ss-member-info"><b>{displayName(u)}</b><small>@{u.username} · {m.role}</small></div>{owner&&<IconCrown size={17}/>} {isOwner&&!owner&&<select className="field-input ss-select" value={m.role||'member'} disabled={busy===m.user_id} onChange={e=>act(m.user_id,()=>api(`/guilds/${guild.id}/members/${m.user_id}/role`,{body:{role:e.target.value}}))}><option value="member">Участник</option><option value="admin">Администратор</option></select>}{canManage&&!owner&&<button className="btn ghost small" disabled={busy===m.user_id} onClick={()=>confirmDialog({title:`Выгнать @${u.username}?`,okLabel:'Выгнать',danger:true,onOk:()=>act(m.user_id,()=>api(`/guilds/${guild.id}/members/${m.user_id}`,{method:'DELETE'}))})}>Выгнать</button>}</div>})}</div></Section>}

function Channels({guild,canManage}){const [selected,setSelected]=useState(guild.channels?.[0]?.id||null);const c=guild.channels?.find(x=>x.id===selected);const [topic,setTopic]=useState(c?.topic||'');const [slow,setSlow]=useState(c?.slowmode_seconds||0);useEffect(()=>{setTopic(c?.topic||'');setSlow(c?.slowmode_seconds||0)},[selected,c?.topic,c?.slowmode_seconds]);const save=async()=>{if(!c)return;try{await api(`/channels/${c.id}/settings`,{method:'PATCH',body:{topic,slowmode_seconds:Number(slow)}});refreshGuild(guild.id)}catch(e){alert(e.message)}};return <div className="ss-two"><div className="ss-channel-list"><div className="ss-toolbar"><b>Каналы</b>{canManage&&<button className="btn ghost small" onClick={()=>setUI({modal:{type:'create-channel',guildId:guild.id,channelType:'text'}})}><IconPlus size={16}/></button>}</div>{guild.channels?.map(x=><button key={x.id} className={selected===x.id?'active':''} onClick={()=>setSelected(x.id)}>{x.type==='voice'?<IconSpeaker size={17}/>:<IconHash size={17}/>}<span>{x.name}</span></button>)}</div><div>{c?<Section title={`Настройки #${c.name}`} desc="Права доступа и параметры канала."><Input label="Тема канала" value={topic} disabled={!canManage} onChange={e=>setTopic(e.target.value)}/>{c.type==='text'&&<label className="ss-field"><span>Медленный режим</span><select className="field-input" disabled={!canManage} value={slow} onChange={e=>setSlow(e.target.value)}><option value="0">Выключен</option><option value="5">5 секунд</option><option value="10">10 секунд</option><option value="30">30 секунд</option><option value="60">1 минута</option><option value="300">5 минут</option><option value="900">15 минут</option></select></label>}{canManage&&<Button onClick={save}>Сохранить канал</Button>}</Section>:<div className="ss-empty">Выберите канал</div>}</div></div>}

function Invites({guild,canManage}){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const load=()=>api(`/guilds/${guild.id}/invites`).then(r=>setItems(r.invites||[])).catch(()=>setItems([])).finally(()=>setLoading(false));useEffect(()=>{load()},[guild.id]);const create=async()=>{try{await api(`/guilds/${guild.id}/invites`,{body:{max_uses:0}});load()}catch(e){alert(e.message)}};return <Section title="Приглашения" desc="Управление активными приглашениями."><div className="ss-toolbar"><span>{items.length} приглашений</span>{canManage&&<Button onClick={create}><IconPlus size={17}/> Создать приглашение</Button>}</div>{loading?<div className="ss-empty">Загрузка…</div>:items.map(i=><div className="ss-invite-row" key={i.code}><code>{i.code}</code><span>{i.uses||0}{i.max_uses?` / ${i.max_uses}`:' использований'}</span><button className="btn ghost small" onClick={()=>navigator.clipboard?.writeText(i.code)}>Копировать</button>{canManage&&<button className="btn red small" onClick={async()=>{await api(`/guilds/${guild.id}/invites/${i.code}`,{method:'DELETE'});load()}}>Отозвать</button>}</div>)}</Section>}

function Bans({guild,canManage}){const [bans,setBans]=useState([]);const [loading,setLoading]=useState(true);const load=()=>api(`/guilds/${guild.id}/bans`).then(r=>setBans(r.bans||[])).catch(()=>setBans([])).finally(()=>setLoading(false));useEffect(()=>{load()},[guild.id]);return <Section title="Баны" desc="Заблокированные пользователи не могут присоединиться к серверу.">{loading?<div className="ss-empty">Загрузка…</div>:bans.length===0?<div className="ss-empty">Банов нет</div>:bans.map(b=><div className="ss-ban" key={b.user_id}><div><b>@{b.username}</b><span>{b.reason||'Причина не указана'}</span></div>{canManage&&<button className="btn ghost small" onClick={async()=>{await api(`/guilds/${guild.id}/bans/${b.user_id}`,{method:'DELETE'});load()}}>Разбанить</button>}</div>)}</Section>}

function AutoMod({guild,canManage}){const key=`dsh_automod_${guild.id}`;const [cfg,setCfg]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||{spam:true,links:false,caps:false,mentions:true,raid:true}}catch{return {spam:true,links:false,caps:false,mentions:true,raid:true}}});useEffect(()=>localStorage.setItem(key,JSON.stringify(cfg)),[cfg,key]);return <Section title="AutoMod" desc="Автоматические правила защиты сервера. Настройки сохраняются отдельно для каждого сервера.">{[['spam','Защита от спама','Блокировать повторяющиеся сообщения'],['links','Фильтр ссылок','Ограничивать ссылки от новых участников'],['caps','Фильтр CAPS','Снижать сообщения с большим количеством заглавных букв'],['mentions','Анти mention-spam','Ограничивать массовые упоминания'],['raid','Защита от рейдов','Усилить ограничения при резком росте активности']].map(([id,t,d])=><label className="ss-toggle" key={id}><div><b>{t}</b><span>{d}</span></div><input type="checkbox" disabled={!canManage} checked={!!cfg[id]} onChange={e=>setCfg({...cfg,[id]:e.target.checked})}/><i/></label>)}</Section>}

function Audit({guild,canManage}){const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);useEffect(()=>{api(`/guilds/${guild.id}/audit-log?limit=100`).then(r=>setRows(r.entries||[])).catch(()=>setRows([])).finally(()=>setLoading(false))},[guild.id]);return <Section title="Журнал аудита" desc="История административных действий сервера.">{!canManage?<div className="ss-empty">Недостаточно прав.</div>:loading?<div className="ss-empty">Загрузка…</div>:rows.length===0?<div className="ss-empty">Действий пока нет</div>:<div className="ss-audit">{rows.map((r,i)=><div key={r.id||i}><div className="ss-audit-icon"><IconBadge size={16}/></div><div><b>{r.action}</b><span>{r.username?`@${r.username}`:'Система'} · {r.created_at?new Date(r.created_at).toLocaleString('ru-RU'):''}</span></div></div>)}</div>}</Section>}

function Integrations({canManage}){const [webhooks,setWebhooks]=useState(()=>{try{return JSON.parse(localStorage.getItem('dsh_integrations')||'[]')}catch{return[]}});const [name,setName]=useState('');const add=()=>{if(!name.trim())return;const n=[...webhooks,{id:crypto.randomUUID(),name:name.trim()}];setWebhooks(n);localStorage.setItem('dsh_integrations',JSON.stringify(n));setName('')};return <Section title="Интеграции" desc="Управление подключениями и внешними сервисами."><div className="ss-integration-add"><input className="field-input" placeholder="Название интеграции" value={name} onChange={e=>setName(e.target.value)}/><Button disabled={!canManage||!name.trim()} onClick={add}>Добавить</Button></div>{webhooks.length===0?<div className="ss-empty">Интеграций пока нет.</div>:webhooks.map(w=><div className="ss-integration" key={w.id}><div><b>{w.name}</b><span>Подключение настроено локально</span></div><button className="btn red small" disabled={!canManage} onClick={()=>{const n=webhooks.filter(x=>x.id!==w.id);setWebhooks(n);localStorage.setItem('dsh_integrations',JSON.stringify(n))}}>Удалить</button></div>)}</Section>}
